# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commande.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommandeMainWindow(object):
    def setupUi(self, CommandeMainWindow):
        CommandeMainWindow.setObjectName("CommandeMainWindow")
        CommandeMainWindow.resize(488, 618)
        CommandeMainWindow.setStyleSheet("background-color: rgb(170, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(CommandeMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.numero = QtWidgets.QLineEdit(self.centralwidget)
        self.numero.setGeometry(QtCore.QRect(30, 100, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numero.setFont(font)
        self.numero.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.numero.setText("")
        self.numero.setObjectName("numero")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(180, 480, 121, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.numtable = QtWidgets.QLineEdit(self.centralwidget)
        self.numtable.setGeometry(QtCore.QRect(250, 100, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numtable.setFont(font)
        self.numtable.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.numtable.setObjectName("numtable")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(330, 480, 121, 71))
        self.Add_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("#Add_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Add_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Add_btn.setObjectName("Add_btn")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(30, 480, 121, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.total = QtWidgets.QLineEdit(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(30, 200, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total.setFont(font)
        self.total.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.total.setObjectName("total")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 340, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.YesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.YesBtn.setGeometry(QtCore.QRect(170, 300, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.YesBtn.setFont(font)
        self.YesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.YesBtn.setStyleSheet("#YesBtn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#YesBtn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.YesBtn.setObjectName("YesBtn")
        self.NoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NoBtn.setGeometry(QtCore.QRect(170, 380, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.NoBtn.setFont(font)
        self.NoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NoBtn.setStyleSheet("#NoBtn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#NoBtn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.NoBtn.setObjectName("NoBtn")
        self.listarticle = QtWidgets.QListView(self.centralwidget)
        self.listarticle.setGeometry(QtCore.QRect(250, 230, 201, 241))
        self.listarticle.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-color: rgb(17, 40, 255);\n"
"background-color: rgb(194, 254, 255);")
        self.listarticle.setObjectName("listarticle")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 190, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        CommandeMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CommandeMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 488, 29))
        self.menubar.setObjectName("menubar")
        CommandeMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CommandeMainWindow)
        self.statusbar.setObjectName("statusbar")
        CommandeMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CommandeMainWindow)
        QtCore.QMetaObject.connectSlotsByName(CommandeMainWindow)

    def retranslateUi(self, CommandeMainWindow):
        _translate = QtCore.QCoreApplication.translate
        CommandeMainWindow.setWindowTitle(_translate("CommandeMainWindow", "MainWindow"))
        self.label_2.setText(_translate("CommandeMainWindow", "Écran Commande"))
        self.numero.setPlaceholderText(_translate("CommandeMainWindow", "numero"))
        self.Search_btn.setText(_translate("CommandeMainWindow", "Search "))
        self.numtable.setPlaceholderText(_translate("CommandeMainWindow", "num table"))
        self.Add_btn.setText(_translate("CommandeMainWindow", "Add "))
        self.Delete_btn.setText(_translate("CommandeMainWindow", "Delete "))
        self.total.setPlaceholderText(_translate("CommandeMainWindow", "total"))
        self.label.setText(_translate("CommandeMainWindow", "Payer :"))
        self.YesBtn.setText(_translate("CommandeMainWindow", "Yes"))
        self.NoBtn.setText(_translate("CommandeMainWindow", "No"))
        self.label_3.setText(_translate("CommandeMainWindow", " liste articles commandés"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CommandeMainWindow = QtWidgets.QMainWindow()
    ui = Ui_CommandeMainWindow()
    ui.setupUi(CommandeMainWindow)
    CommandeMainWindow.show()
    sys.exit(app.exec_())
