# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuMainWindow(object):
    def setupUi(self, MenuMainWindow):
        MenuMainWindow.setObjectName("MenuMainWindow")
        MenuMainWindow.resize(492, 618)
        MenuMainWindow.setStyleSheet("background-color: rgb(0, 85, 127);")
        self.centralwidget = QtWidgets.QWidget(MenuMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(40, 470, 121, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.prix = QtWidgets.QLineEdit(self.centralwidget)
        self.prix.setGeometry(QtCore.QRect(260, 230, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.prix.setFont(font)
        self.prix.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.prix.setObjectName("prix")
        self.nomarticle = QtWidgets.QLineEdit(self.centralwidget)
        self.nomarticle.setGeometry(QtCore.QRect(260, 110, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nomarticle.setFont(font)
        self.nomarticle.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.nomarticle.setObjectName("nomarticle")
        self.numarticle = QtWidgets.QLineEdit(self.centralwidget)
        self.numarticle.setGeometry(QtCore.QRect(40, 110, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numarticle.setFont(font)
        self.numarticle.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.numarticle.setText("")
        self.numarticle.setObjectName("numarticle")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(190, 470, 121, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(340, 470, 121, 71))
        self.Add_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("#Add_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Add_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Add_btn.setObjectName("Add_btn")
        self.type = QtWidgets.QLineEdit(self.centralwidget)
        self.type.setGeometry(QtCore.QRect(40, 230, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.type.setFont(font)
        self.type.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.type.setObjectName("type")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 340, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        MenuMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MenuMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 29))
        self.menubar.setObjectName("menubar")
        MenuMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MenuMainWindow)
        self.statusbar.setObjectName("statusbar")
        MenuMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MenuMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MenuMainWindow)

    def retranslateUi(self, MenuMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuMainWindow.setWindowTitle(_translate("MenuMainWindow", "MainWindow"))
        self.Delete_btn.setText(_translate("MenuMainWindow", "Delete "))
        self.label_2.setText(_translate("MenuMainWindow", "Écran Menu"))
        self.prix.setPlaceholderText(_translate("MenuMainWindow", "Prix"))
        self.nomarticle.setPlaceholderText(_translate("MenuMainWindow", " nom article"))
        self.numarticle.setPlaceholderText(_translate("MenuMainWindow", "num article"))
        self.Search_btn.setText(_translate("MenuMainWindow", "Search "))
        self.Add_btn.setText(_translate("MenuMainWindow", "Add "))
        self.type.setPlaceholderText(_translate("MenuMainWindow", "type"))
        self.label_3.setText(_translate("MenuMainWindow", "Photo IDK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MenuMainWindow = QtWidgets.QMainWindow()
    ui = Ui_MenuMainWindow()
    ui.setupUi(MenuMainWindow)
    MenuMainWindow.show()
    sys.exit(app.exec_())
