# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablecontient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tablecontientMainWindow(object):
    def setupUi(self, tablecontientMainWindow):
        tablecontientMainWindow.setObjectName("tablecontientMainWindow")
        tablecontientMainWindow.resize(494, 614)
        tablecontientMainWindow.setStyleSheet("background-color: rgb(138, 145, 213);")
        self.centralwidget = QtWidgets.QWidget(tablecontientMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.numero = QtWidgets.QLineEdit(self.centralwidget)
        self.numero.setGeometry(QtCore.QRect(30, 120, 421, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.numero.setFont(font)
        self.numero.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.numero.setText("")
        self.numero.setObjectName("numero")
        self.etage = QtWidgets.QLineEdit(self.centralwidget)
        self.etage.setGeometry(QtCore.QRect(30, 240, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.etage.setFont(font)
        self.etage.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.etage.setObjectName("etage")
        self.nbrchaises = QtWidgets.QLineEdit(self.centralwidget)
        self.nbrchaises.setGeometry(QtCore.QRect(250, 240, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nbrchaises.setFont(font)
        self.nbrchaises.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: rgb(17, 40, 255);\n"
"padding-bottom:7px;\n"
"background-color: rgb(194, 254, 255);")
        self.nbrchaises.setObjectName("nbrchaises")
        self.YesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.YesBtn.setGeometry(QtCore.QRect(370, 350, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.YesBtn.setFont(font)
        self.YesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.YesBtn.setStyleSheet("#YesBtn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#YesBtn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.YesBtn.setObjectName("YesBtn")
        self.NoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NoBtn.setGeometry(QtCore.QRect(250, 350, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.NoBtn.setFont(font)
        self.NoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NoBtn.setStyleSheet("#NoBtn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#NoBtn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.NoBtn.setObjectName("NoBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 350, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.Search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Search_btn.setGeometry(QtCore.QRect(180, 480, 121, 71))
        self.Search_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Search_btn.setFont(font)
        self.Search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search_btn.setStyleSheet("#Search_btn{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(60, 255, 39);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(3, 168, 17);\n"
"}\n"
"#Search_btn:hover:pressed{\n"
"background-color: rgb(126, 255, 103);\n"
"}")
        self.Search_btn.setObjectName("Search_btn")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(330, 480, 121, 71))
        self.Add_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("#Add_btn{\n"
"background-color: rgb(112, 162, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"border: 3px Solid rgb(17, 21, 255);\n"
"}\n"
"#Add_btn:hover:pressed{\n"
"background-color: rgb(190, 164, 255);\n"
"}")
        self.Add_btn.setObjectName("Add_btn")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(30, 480, 121, 71))
        self.Delete_btn.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("#Delete_btn{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 18px;\n"
"background-color: rgb(255, 2, 14);\n"
"border: 3px Solid rgb(175, 34, 15);\n"
"}\n"
"#Delete_btn:hover:pressed{\n"
"background-color: rgb(255, 167, 43);\n"
"}\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        tablecontientMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tablecontientMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 29))
        self.menubar.setObjectName("menubar")
        tablecontientMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tablecontientMainWindow)
        self.statusbar.setObjectName("statusbar")
        tablecontientMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(tablecontientMainWindow)
        QtCore.QMetaObject.connectSlotsByName(tablecontientMainWindow)

    def retranslateUi(self, tablecontientMainWindow):
        _translate = QtCore.QCoreApplication.translate
        tablecontientMainWindow.setWindowTitle(_translate("tablecontientMainWindow", "MainWindow"))
        self.numero.setPlaceholderText(_translate("tablecontientMainWindow", "Number"))
        self.etage.setPlaceholderText(_translate("tablecontientMainWindow", "étage"))
        self.nbrchaises.setPlaceholderText(_translate("tablecontientMainWindow", "nombre brchaises"))
        self.YesBtn.setText(_translate("tablecontientMainWindow", "Yes "))
        self.NoBtn.setText(_translate("tablecontientMainWindow", "No "))
        self.label.setText(_translate("tablecontientMainWindow", "smoking area :"))
        self.label_2.setText(_translate("tablecontientMainWindow", "Ecran Table contient"))
        self.Search_btn.setText(_translate("tablecontientMainWindow", "Search "))
        self.Add_btn.setText(_translate("tablecontientMainWindow", "Add "))
        self.Delete_btn.setText(_translate("tablecontientMainWindow", "Delete "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tablecontientMainWindow = QtWidgets.QMainWindow()
    ui = Ui_tablecontientMainWindow()
    ui.setupUi(tablecontientMainWindow)
    tablecontientMainWindow.show()
    sys.exit(app.exec_())
